version: "3.7"

services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  simple_nutch:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./simple_nutch
        target: /opt/app/simple_nutch
    ports:
      - '8010:8010'
